<template>
  <div class="editor-page" v-loading="loading">
    <header class="page-header"><div><el-button text :icon="ArrowLeft" @click="goBack">返回知识库</el-button><span class="eyebrow">KNOWLEDGE EDITOR</span><h1>{{ editing ? '编辑售后知识' : '新建售后知识' }}</h1><p>按照标准模板填写，保存后自动生成 Markdown 并重建检索索引。</p></div><div class="header-actions"><el-button :icon="Download" :loading="previewing" @click="downloadMarkdown">下载 Markdown</el-button><el-button type="primary" :icon="Check" :loading="saving" @click="saveArticle">保存到知识库</el-button></div></header>
    <div class="progress"><div><strong>填写进度</strong><span>{{ completedRequired }}/{{ requiredFields.length }} 个必填项</span></div><el-progress :percentage="progress" :stroke-width="8" /></div>
    <el-form ref="formRef" :model="form" :rules="rules" label-position="top" class="layout">
      <main class="sections">
        <el-card shadow="never"><template #header><SectionTitle number="01" title="基础信息" description="定义唯一编号、故障标题和适用范围" /></template>
          <div class="grid"><el-form-item label="问题编号" prop="question_id"><el-input v-model="form.question_id" maxlength="40" placeholder="例如：NET-001" /></el-form-item><el-form-item label="问题分类" prop="category"><el-select v-model="form.category" placeholder="请选择"><el-option v-for="item in categories" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item class="full" label="问题标题" prop="title"><el-input v-model="form.title" maxlength="120" placeholder="产品/功能 + 故障现象" /></el-form-item><el-form-item class="full" label="适用产品类型" prop="product_type"><el-input v-model="form.product_type" placeholder="例如：云网管 PoE 交换机" /></el-form-item></div>
          <ListField v-model="form.applicable_models" label="适用型号" placeholder="通用，或具体型号及范围" required /><ListField v-model="form.excluded_models" label="不适用型号（可选）" placeholder="明确不适用的型号" />
        </el-card>
        <el-card shadow="never"><template #header><SectionTitle number="02" title="客户表达与检索" description="覆盖真实问法并提供准确检索信号" /></template>
          <ListField v-model="form.english_expressions" label="客户常见英文表达" placeholder="The device appears offline after I add it." /><ListField v-model="form.chinese_expressions" label="客户常见中文表达" placeholder="添加设备后显示离线" />
          <el-form-item label="中文标准问题" prop="standard_question"><el-input v-model="form.standard_question" type="textarea" :rows="3" placeholder="完整描述客户问题，不写解决方案" /></el-form-item><el-form-item label="检索关键词" prop="keywords"><el-input v-model="form.keywords" type="textarea" :rows="2" placeholder="故障现象、动作、功能名和型号，用逗号分隔" /></el-form-item>
          <ListField v-model="form.conditions" label="故障判断条件" placeholder="满足什么现象时适用" /><ListField v-model="form.causes" label="已确认的可能原因" placeholder="仅填写经过验证的原因" />
        </el-card>
        <el-card shadow="never"><template #header><SectionTitle number="03" title="解决方案" description="通用步骤与型号专用步骤严格分开" /></template>
          <ListField v-model="form.general_steps" label="通用解决方案" placeholder="每项只填写一个动作" ordered />
          <div class="variant-title"><div><strong>分型号解决方案（可选）</strong><p>只有确认具体型号后才能使用。</p></div><el-button type="primary" plain @click="addVariant">新增型号方案</el-button></div>
          <div v-for="(variant,index) in form.model_solutions" :key="index" class="variant"><div class="variant-head"><strong>型号方案 {{ index+1 }}</strong><el-button type="danger" text @click="form.model_solutions.splice(index,1)">删除</el-button></div><el-input v-model="variant.model" placeholder="型号或系列，例如：GS105、GS108" /><ListField v-model="variant.steps" label="专用步骤" placeholder="该型号专用的操作步骤" ordered /></div>
        </el-card>
        <el-card shadow="never"><template #header><SectionTitle number="04" title="安全边界" description="明确风险、信息缺口和转人工条件" /></template>
          <el-form-item label="操作风险" prop="risk"><el-input v-model="form.risk" type="textarea" :rows="3" placeholder="没有风险写“无”；危险操作必须说明影响" /></el-form-item><ListField v-model="form.required_information" label="需要客户补充的信息" placeholder="继续判断所必需的信息" /><ListField v-model="form.escalation_conditions" label="转人工条件" placeholder="不得继续自动操作的情况" /><ListField v-model="form.reply_restrictions" label="禁止回复或限制条件" placeholder="未确认型号时的限制等" />
        </el-card>
        <el-card shadow="never"><template #header><SectionTitle number="05" title="回复参考与来源" description="提供英文表达参考并记录可追溯来源" /></template>
          <el-form-item label="标准英文回复参考" prop="english_reply"><el-input v-model="form.english_reply" type="textarea" :rows="8" placeholder="填写基于证据的英文回复，签名会规范为 Technical Support" /></el-form-item><div class="grid source"><el-form-item label="来源名称"><el-input v-model="form.source.name" /></el-form-item><el-form-item label="版本或日期"><el-input v-model="form.source.version" /></el-form-item><el-form-item label="维护人"><el-input v-model="form.source.maintainer" /></el-form-item></div>
        </el-card>
      </main>
      <aside class="preview"><div class="preview-head"><div><strong>Markdown 预览</strong><small>{{ suggestedFilename || '填写必填项后生成文件名' }}</small></div><el-button text :loading="previewing" @click="refreshPreview">刷新</el-button></div><pre>{{ markdown || '完成必填项后，点击“刷新”查看规范文档。' }}</pre></aside>
    </el-form>
  </div>
</template>
<script setup>
import { computed, defineComponent, h, onMounted, reactive, ref, watch } from 'vue'
import { onBeforeRouteLeave, useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowLeft, Check, Download } from '@element-plus/icons-vue'
import { knowledgeApi } from '@/api/knowledge'
import ListField from '@/components/KnowledgeListField.vue'
const SectionTitle=defineComponent({props:{number:String,title:String,description:String},setup:p=>()=>h('div',{class:'section-title'},[h('span',p.number),h('div',[h('h2',p.title),h('p',p.description)])])})
const emptyForm=()=>({question_id:'',title:'',category:'',product_type:'',applicable_models:[''],excluded_models:[],english_expressions:['','',''],chinese_expressions:['','',''],standard_question:'',keywords:'',conditions:[''],causes:[''],general_steps:['','',''],model_solutions:[],risk:'',required_information:[''],escalation_conditions:[''],reply_restrictions:[''],english_reply:'',source:{name:'',version:'',maintainer:''}})
const route=useRoute(),router=useRouter(),formRef=ref(),form=reactive(emptyForm()),loading=ref(false),saving=ref(false),previewing=ref(false),markdown=ref(''),suggestedFilename=ref(''),originalFilename=ref(''),dirty=ref(false),initialized=ref(false)
const editing=computed(()=>Boolean(route.params.filename)),draftKey=computed(()=>`knowledge-article-draft:${originalFilename.value||'new'}`)
const categories=['技术参数咨询','安装配置','使用指导','故障排查','网络连接','软件固件','兼容性问题'],requiredFields=['question_id','title','category','product_type','standard_question','keywords','risk','english_reply']
const completedRequired=computed(()=>requiredFields.filter(k=>String(form[k]||'').trim()).length),progress=computed(()=>Math.round(completedRequired.value/requiredFields.length*100)),rules=Object.fromEntries(requiredFields.map(k=>[k,[{required:true,message:'此项为必填项',trigger:'blur'}]]))
const assignForm=data=>{Object.assign(form,emptyForm(),data);form.source={...emptyForm().source,...(data.source||{})}},payload=()=>JSON.parse(JSON.stringify(form)),addVariant=()=>form.model_solutions.push({model:'',steps:['']})
const refreshPreview=async()=>{previewing.value=true;try{const data=await knowledgeApi.previewArticle(payload());markdown.value=data.markdown;suggestedFilename.value=data.filename;return data}finally{previewing.value=false}}
const downloadMarkdown=async()=>{const data=await refreshPreview(),url=URL.createObjectURL(new Blob([data.markdown],{type:'text/markdown;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=data.filename;link.click();URL.revokeObjectURL(url)}
const saveArticle=async()=>{await formRef.value.validate();saving.value=true;try{const data=editing.value?await knowledgeApi.updateArticle(originalFilename.value,payload()):await knowledgeApi.createArticle(payload());dirty.value=false;localStorage.removeItem(draftKey.value);ElMessage.success(data.message);router.push('/knowledge')}finally{saving.value=false}},goBack=()=>router.push('/knowledge')
watch(form,()=>{if(initialized.value){dirty.value=true;localStorage.setItem(draftKey.value,JSON.stringify(payload()))}},{deep:true})
onBeforeRouteLeave(async()=>{if(!dirty.value)return true;try{await ElMessageBox.confirm('当前内容尚未保存，离开后仍会保留本地草稿。确认离开？','未保存的更改',{type:'warning'});return true}catch{return false}})
onMounted(async()=>{loading.value=true;try{if(editing.value){originalFilename.value=String(route.params.filename);assignForm((await knowledgeApi.getArticle(originalFilename.value)).article);const draft=localStorage.getItem(draftKey.value);if(draft)try{assignForm(JSON.parse(draft));ElMessage.info('已恢复此文档上次未保存的本地草稿')}catch{localStorage.removeItem(draftKey.value)}}else{const draft=localStorage.getItem(draftKey.value);if(draft)try{assignForm(JSON.parse(draft));ElMessage.info('已恢复上次未保存的本地草稿')}catch{localStorage.removeItem(draftKey.value)}}}finally{initialized.value=true;loading.value=false}})
</script>
<style scoped>
.editor-page{max-width:1600px;margin:0 auto}.page-header{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-bottom:20px}.page-header>div:first-child>.el-button{display:block;margin:0 0 10px -15px}.eyebrow{display:block;margin-bottom:7px;color:#2563eb;font-size:11px;font-weight:800;letter-spacing:.14em}h1{margin:0;color:#182230;font-size:28px}.page-header p{margin:7px 0 0;color:#667085;font-size:13px}.header-actions{display:flex;gap:10px}.progress{margin-bottom:20px;padding:16px 20px;border:1px solid #dbe5f3;border-radius:12px;background:#fff}.progress>div{display:flex;justify-content:space-between;margin-bottom:10px;color:#344054}.progress span{color:#667085;font-size:13px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 420px;align-items:start;gap:20px}.sections{display:flex;flex-direction:column;gap:20px}.sections :deep(.el-card){border:1px solid #e5eaf2}.section-title{display:flex;align-items:center;gap:12px}.section-title>span{display:grid;place-items:center;width:34px;height:34px;border-radius:9px;background:#eff6ff;color:#2563eb;font-weight:800}.section-title h2{margin:0;color:#182230;font-size:17px}.section-title p{margin:4px 0 0;color:#667085;font-size:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 18px}.grid .full{grid-column:1/-1}.grid :deep(.el-select){width:100%}.source{grid-template-columns:repeat(3,1fr)}.variant-title,.variant-head{display:flex;align-items:center;justify-content:space-between}.variant-title{margin:6px 0 12px}.variant-title p{margin:4px 0 0;color:#98a2b3;font-size:12px}.variant{margin-bottom:12px;padding:14px;border:1px solid #dbe5f3;border-radius:10px;background:#fafcff}.variant-head{margin-bottom:10px;color:#344054}.variant :deep(.list-field){margin:16px 0 0}.preview{position:sticky;top:20px;min-width:0;border:1px solid #dbe5f3;border-radius:12px;background:#111827;overflow:hidden}.preview-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;background:#182230;color:#fff}.preview-head strong,.preview-head small{display:block}.preview-head small{max-width:290px;margin-top:4px;overflow:hidden;color:#98a2b3;font-size:11px;text-overflow:ellipsis;white-space:nowrap}.preview-head :deep(.el-button){color:#93c5fd}.preview pre{min-height:560px;max-height:calc(100vh - 170px);margin:0;padding:18px;overflow:auto;color:#d1d5db;font:12px/1.65 Consolas,monospace;white-space:pre-wrap;word-break:break-word}@media(max-width:1150px){.layout{grid-template-columns:1fr}.preview{position:static}.preview pre{min-height:320px;max-height:600px}}@media(max-width:700px){.page-header{align-items:flex-start;flex-direction:column}.header-actions{width:100%}.header-actions .el-button{flex:1}.grid,.source{grid-template-columns:1fr}.grid .full{grid-column:auto}.sections :deep(.el-card__body){padding:16px}}
</style>
